AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/spring'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'bin/yarn'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
Style/SymbolArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericLiterals:
  Description: Add underscores to large numeric literals to improve their readability.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics
  Enabled: false
Metrics/MethodLength:
  Description: Avoid methods longer than 15 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Enabled: true
  CountComments: true
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments, branches, and
    conditions.
  Enabled: true
  Max: 25
  Exclude:
    - 'db/**/*'
Style/StringLiterals:
  StyleGuide: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/StringLiterals
  Enabled: true
  Exclude:
    - 'db/**/*'
    - 'test/models/**/*'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'db/**/*'
    - 'config/environments/**/*'
    - 'app/active_admin/**/*'
Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'app/models/**/*'
Style/FormatString:
  Description: Enforce the use of Kernel#sprintf, Kernel#format or String#%.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#sprintf
  Enabled: false
  EnforcedStyle: format
  SupportedStyles:
    - format
    - sprintf
    - percent
Style/ClassVars:
  Description: Avoid the use of class variables.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-class-vars
  Enabled: false
Style/MultilineBlockChain:
  Description: Avoid multi-line chains of blocks.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#single-line-blocks
  Enabled: false
Style/Lambda:
  Enabled: false
